title: paul warren dot net
description: discussions on program and project management, opinions on tech and business leadership
url: "https://warrewp.github.io"
baseurl: "/pwdotcom"

permalink: /:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
